/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        clr: {
          Primary1: '#363738',
          Secondary: '#F5F5F5',
          Secondary1: '#FEFAF1',
          Secondary2: '#DB4444',
          Text: '#FAFAFA',
          Text1: '#7D8184',
          ButtonGreen: '#00FF66',
          ButtonRed: '#DB4444',
          HoverButtonRed: '#E07575',
          HoverButtonBlue: '#A0BCE0',
        },
      },
      fontFamily: {
        'heading-sans': ['Inter', 'sans-serif'],
        'heading-medium': ['InterMedium', 'sans-serif'],
        'heading-semibold': ['InterSemibold', 'sans-serif'],
        'heading-bold': ['InterBold', 'sans-serif'],
        sans: ['Poppins', 'sans-serif'],
        medium: ['PoppinsMedium', 'sans-serif'],
        semibold: ['PoppinsSemibold', 'sans-serif'],
      },
    },
    fontSize: {
      '2xs': '.625rem',
      xs: '.75rem',
      sm: '.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
      '7xl': '5rem',
      24: '1.5rem',
      32: '2rem',
      36: '2.25rem',
      48: '3rem',
      54: '3.375rem',
      64: '4rem',
      90: '5.625rem',
      110: '6.875rem',
    },
  },
  plugins: [],
};
