import {
  IconPhone,
  IconComputer,
  IconSmartWatch,
  IconCamera,
  IconHeadPhone,
  IconGaming,
} from '@ui/components/icons';

export const categories = [
  {
    name: 'Phone',
    url: '/categories/phone',
    Icon: IconPhone,
  },
  {
    name: 'Computer',
    url: '/categories/computer',
    Icon: IconComputer,
  },
  {
    name: 'SmartWatch',
    url: '/categories/smartwatch',
    Icon: IconSmartWatch,
  },
  {
    name: 'Camera',
    url: '/categories/camera',
    Icon: IconCamera,
  },
  {
    name: 'Headphone',
    url: '/categories/headphone',
    Icon: IconHeadPhone,
  },
  {
    name: 'Gaming',
    url: '/categories/gaming',
    Icon: IconGaming,
  },
];
export const products = [
  {
    id: 0,
    name: 'HAVIT HV-G92 Gamepad',
    rating: 5.0,
    ratingCount: 88,
    price: 160,
    discount: 40,
  },
  {
    id: 1,
    name: 'AK-900 Wired Keyboard',
    rating: 4.0,
    ratingCount: 75,
    price: 1160,
    discount: 35,
  },
  {
    id: 2,
    name: 'IPS LCD Gaming Monitor',
    rating: 5.0,
    ratingCount: 99,
    price: 400,
    discount: 30,
  },
  {
    id: 3,
    name: 'S-Series Comfort Chair',
    rating: 4.5,
    ratingCount: 99,
    price: 400,
    discount: 25,
  },
  /*

*/
  {
    id: 4,
    name: 'The north coat',
    rating: 5.0,
    ratingCount: 65,
    price: 260,
    discount: 0,
  },
  {
    id: 5,
    name: 'Gucci duffle bag',
    rating: 4.5,
    ratingCount: 65,
    price: 960,
    discount: 0,
  },
  {
    id: 6,
    name: 'RGB liquid CPU Cooler',
    rating: 4.5,
    ratingCount: 65,
    price: 160,
    discount: 0,
  },
  {
    id: 7,
    name: 'Small BookSelf',
    rating: 5.0,
    ratingCount: 65,
    price: 360,
    discount: 0,
  },
  {
    id: 8,
    name: 'Breed Dry Dog Food',
    rating: 3.0,
    ratingCount: 35,
    price: 100,
    discount: 0,
  },
  {
    id: 9,
    name: 'CANON EOS DSLR Camera',
    rating: 4.0,
    ratingCount: 95,
    price: 360,
    discount: 0,
  },
  {
    id: 10,
    name: 'ASUS FHD Gaming Laptop',
    rating: 5.0,
    ratingCount: 325,
    price: 700,
    discount: 0,
  },
  {
    id: 11,
    name: 'Curology Product Set',
    rating: 4.0,
    ratingCount: 145,
    price: 500,
    discount: 0,
  },
  {
    id: 12,
    name: 'Kids Electric Car',
    rating: 5.0,
    ratingCount: 65,
    price: 960,
    discount: 0,
  },
  {
    id: 13,
    name: 'Jr. Zoom Soccer Cleats',
    rating: 5.0,
    ratingCount: 35,
    price: 1160,
    discount: 0,
  },
  {
    id: 14,
    name: 'GP11 Shooter USB Gamepad',
    rating: 4.5,
    ratingCount: 55,
    price: 660,
    discount: 0,
  },
  {
    id: 15,
    name: 'Quilted Satin Jacket',
    rating: 4.5,
    ratingCount: 55,
    price: 660,
    discount: 0,
  },
];
